Add AWS App Runner deployment workflow***
***Update Dockerfile to set Spring active profile

diff --git a/.github/workflows/aws-workflow.yml b/.github/workflows/aws-workflow.yml
--- a/.github/workflows/aws-workflow.yml
+++ b/.github/workflows/aws-workflow.yml
@@ -56,3 +56,42 @@ jobs:
           docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
           docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
           docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
+      - name: Deploy production with aws CLI
+        if: ${{ inputs.environment }} == 'Production'
+        run: |
+          aws apprunner start-deployment --service-arn="${{ vars.SERVICE_ARN }}"
+
+      - name: Wait for Deployment to Begin
+        run: |
+          STATUS=$(aws apprunner describe-service --query="Service.Status" --output=text --service-arn="${{ vars.SERVICE_ARN }}")
+
+          until [ "${STATUS}" == "OPERATION_IN_PROGRESS" ];
+          do
+            echo "$(date) ${STATUS}"
+            STATUS=$(aws apprunner describe-service --query="Service.Status" --output=text --service-arn="${{ vars.SERVICE_ARN }}")
+            sleep 10;
+          done
+
+      - name: Wait for Deployment to Complete
+        id: status
+        timeout-minutes: 10
+        run: |
+          STATUS=$(aws apprunner describe-service --query="Service.Status" --output=text --service-arn="${{ vars.SERVICE_ARN }}")
+
+          while [ "${STATUS}" == "OPERATION_IN_PROGRESS" ];
+          do
+            echo "$(date) ${STATUS}"
+            STATUS=$(aws apprunner describe-service --query="Service.Status" --output=text --service-arn="${{ vars.SERVICE_ARN }}")
+            sleep 30;
+          done
+          echo "deployment_status=${STATUS}" >> "$GITHUB_OUTPUT"
+
+      - name: Check Deployment Status
+        id: check
+        run: |
+          if [ "${{ steps.status.outputs.deployment_status }}" == "RUNNING" ]; then
+            echo "Deployment successful"
+          else
+            echo "Deployment failed: ${{ steps.status.outputs.deployment_status }}"
+            exit 1
+          fi
